# Basic application info
spring.application.name=class-service
server.port=8084

# Firebase configuration
firebase.project-id=skillnest-db
firebase.credentials.path=firebase.json


# Optional: development logging
logging.level.org.springframework=INFO
logging.level.com.skillnest=DEBUG

# Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-gowthamkulfi@gmail.com
spring.mail.password=bcnszqoecftvbnww
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true