# Basic application info
spring.application.name=class-service
server.port=8084

# Firebase configuration
firebase.project-id=skillnest-db
firebase.credentials.path=firebase.json


# Optional: development logging
logging.level.org.springframework=INFO
logging.level.com.skillnest=DEBUG