# App info
spring.application.name=api-gateway
server.port=8080

# USER SERVICE ROUTE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**,/api/me,/api/health

# COURSE SERVICE ROUTE
spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**
## Basic application info

#spring.application.name=api-gateway
#server.port=8080
#
## Firebase configuration (same for all services)
#firebase.project-id=skillnest-db
#firebase.credentials.path=firebase.json
#
## Gateway routing rules - this makes the gateway forward requests
#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**,/api/auth/**
#
#spring.cloud.gateway.routes[1].id=course-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**
#
#spring.cloud.gateway.routes[2].id=enrollment-service
#spring.cloud.gateway.routes[2].uri=http://localhost:8083
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/enrollments/**
#
#spring.cloud.gateway.routes[3].id=class-service
#spring.cloud.gateway.routes[3].uri=http://localhost:8084
#spring.cloud.gateway.routes[3].predicates[0]=Path=/api/classes/**,/api/availability/**,/api/earnings/**